elgeopaso/api/urls.py
#! python3  # noqa: E265  # noqa E265

"""
    Application URLs settings.

    Learn more here:

    - https://docs.djangoproject.com/fr/2.2/topics/http/urls/
    - https://docs.djangoproject.com/fr/2.2/ref/urls/
"""

# #############################################################################
# ########## Libraries #############
# ##################################

# Django
from django.conf import settings
from django.urls import re_path

# Dajngo REST Framework
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

# application
from elgeopaso.api import views

# #############################################################################
# ########### Globals ##############
# ##################################

# API ROUTING
router = routers.SimpleRouter()

router.register(r"contrats", views.ContractViewSet)
router.register(r"lieux", views.PlaceViewSet)
router.register(r"lieux_variantes", views.PlaceVariationsViewSet)
router.register(r"offres", views.OfferViewSet)
router.register(r"metiers", views.JobViewSet)
router.register(r"technos", views.TechnoViewSet)

urlpatterns = router.urls

# API SWAGGER
schema_view = get_schema_view(
    openapi.Info(
        title="El Géo Paso - Documentation de l'API",
        default_version="v1",
        description="Documentation standardisée de l'API REST d'El Géo Paso",
        terms_of_service="https://blog.georezo.net/laminute/tout-sur-georezo/mentions-legales/",
        contact=openapi.Contact(email=settings.EMAIL_HOST_USER),
    ),
    public=False,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    # OpenAPI files
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=60 * 60),
        name="schema-json",
    ),
    # Swagger UI
    re_path(
        "swagger|docs",
        schema_view.with_ui(renderer="swagger", cache_timeout=60 * 60),
        name="schema-swagger-ui",
    ),
]

elgeopaso/cms/urls.py
#! python3  # noqa: E265  # noqa E265

"""
    Application URLs settings.
"""

# #############################################################################
# ########## Libraries #############
# ##################################

# Django
from django.conf.urls import url

from elgeopaso.cms import views

# #############################################################################
# ########### Globals ##############
# ##################################
urlpatterns = [
    url(r"^about/$", views.about, name="about"),
    url(r"^(?P<slug>[-\w]+)/$", views.view_category, name="view_category"),
    url(
        r"^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$",
        views.view_article,
        name="view_article",
    ),
]

elgeopaso/jobs/urls.py
#! python3  # noqa: E265

"""
    Application URLs settings.

    Learn more here: https://docs.djangoproject.com/fr/2.2/topics/http/urls/
"""

# #############################################################################
# ########## Libraries #############
# ##################################

# Django
from django.urls import path
from django.views.generic import TemplateView

# project
from elgeopaso.jobs import views

# #############################################################################
# ########### Globals ##############
# ##################################
app_name = "jobs"

urlpatterns = [
    path(r"", views.stats_home, name="index"),
    path(r"stats/", views.stats_contrats, name="stats"),
    path(r"timeline/", views.timeline, name="timeline"),
    path(r"search/", views.search, name="search"),
    path(r"map/", TemplateView.as_view(template_name="jobs/map.html"), name="map"),
    # Functions called via AJAX
    path(
        r"stats/get_offers_by_period",
        views.get_offers_by_period,
        name="get_offers_by_period",
    ),
    path(
        r"stats/get_types_contract_by_period",
        views.get_types_contract_by_period,
        name="get_types_contract_by_period",
    ),
    path(
        r"stats/get_contracts_by_technos",
        views.get_contracts_by_technos,
        name="get_contracts_by_technos",
    ),
    path(
        r"stats/get_countries_top5", views.get_countries_top5, name="get_countries_top5"
    ),
    path(r"stats/get_fr_dpts_top10", views.get_fr_dpts_top10, name="get_fr_dpts_top10"),
]

elgeopaso/urls.py
#! python3  # noqa: E265  # noqa E265

"""
    Project URLs settings.

    Learn more here: https://docs.djangoproject.com/fr/2.2/topics/http/urls/

    To add a new path:

    .. code-block:: python

        # first import the app
        import jobs

        # then add the new path:
        path('jobs/', jobs.urls, name="Jobs offers")

"""

# #############################################################################
# ########## Libraries #############
# ##################################

# Django
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

# #############################################################################
# ########### Globals ##############
# ##################################
admin.autodiscover()


# List of accepted URLs
urlpatterns = [
    # administration panel
    path("admin/", admin.site.urls),
    # authentication flow
    path("accounts/", include("allauth.urls")),
    # Jobs analytics
    path("", include("elgeopaso.jobs.urls", "index"), name="home"),
    path("jobs/", include("elgeopaso.jobs.urls")),
    # CMS
    path("content/", include(("elgeopaso.cms.urls", "cms"), namespace="cms")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    # API
    path("api/", include(("elgeopaso.api.urls", "api"), namespace="api")),
]


# Addtionnal configuration for local development
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += [
    #     path(
    #         "400/",
    #         default_views.bad_request,
    #         kwargs={"exception": Exception("Bad Request!")},
    #     ),
    #     path(
    #         "403/",
    #         default_views.permission_denied,
    #         kwargs={"exception": Exception("Permission Denied")},
    #     ),
    #     path(
    #         "404/",
    #         default_views.page_not_found,
    #         kwargs={"exception": Exception("Page not Found")},
    #     ),
    #     path("500/", default_views.server_error),
    # ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

elgeopaso/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


# Users
class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    report_hour = models.BooleanField("Rapport horaire", blank=False, default=False)
    report_week = models.BooleanField(
        "Rapport hebdomadaire", blank=False, default=False
    )

    def __str__(self):
        if self.report_hour and self.report_week:
            return "Utilisateur.rice abonné.e aux rapports horaires" " et hebdomadaires"
        elif self.report_hour:
            return "Utilisateur.rice abonné.e aux rapports horaires"
        elif self.report_week:
            return "Utilisateur.rice abonné.e aux rapports hebdomadaires"
        else:
            return "L'utilisateur.rice n'est abonné.e à aucun rapport"

    class Meta:
        app_label = "accounts"
        verbose_name = "Abonnements mail"

elgeopaso/cms/models.py
# 3rd party package
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator
from django.db import models
from django.template.defaultfilters import truncatechars
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Catégorie")
    slug_name = models.SlugField(verbose_name="Alias normé", unique=True, blank=True)
    description = models.TextField(blank=True, verbose_name="Description")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("view_category", kwargs={"slug": self.slug_name})

    class Meta:
        app_label = "cms"
        ordering = ["name"]
        verbose_name = "Type de contenu"
        verbose_name_plural = "Types de contenu"


class Article(models.Model):
    # meta
    author = models.ForeignKey(
        User, verbose_name="Auteur.e", null=True, on_delete=models.SET_NULL
    )
    category = models.ForeignKey(
        Category, verbose_name="Catégorie", null=True, on_delete=models.SET_NULL
    )
    # content
    title = models.CharField(
        "Titre", max_length=200, validators=[MaxLengthValidator(200)]
    )
    slug_title = models.SlugField(verbose_name="Alias normé", unique=True, blank=True)
    content = RichTextUploadingField("Corps de texte")
    ext_url = models.URLField("Lien externe", blank=True)
    published = models.BooleanField("Publié", blank=False, default=False)
    # dates
    created = models.DateTimeField("Créé le", auto_now_add=True)
    updated = models.DateTimeField("Modifié le", auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "cms:view_article",
            kwargs={"slug": self.slug_title, "category": self.category.slug_name},
        )
        # return "/content/{}/{}".format(self.category.slug_name, self.slug_title)

    @property
    def short_content(self):
        return truncatechars(self.content, 300)

    class Meta:
        app_label = "cms"
        get_latest_by = "updated"
        ordering = [
            "title",
        ]
        verbose_name = "Contenu éditorial"
        verbose_name_plural = "Contenus éditoriaux"

elgeopaso/api/views.py
#!/usr/bin/env python

# ###########################################################################
# ######### Libraries #############
# #################################
# Standard library

# Django

# REST API
from rest_framework import viewsets

from elgeopaso.api.serializers import (
    ContractSerializer,
    JobSerializer,
    OfferSerializer,
    PlaceSerializer,
    PlaceVariationsSerializer,
    TechnoSerializer,
)

# PROJECT APPS
from elgeopaso.jobs.models import (
    Contract,
    JobPosition,
    Offer,
    Place,
    PlaceVariations,
    Technology,
)

# #############################################################################
# ########## Views ################
# #################################


class ContractViewSet(viewsets.ReadOnlyModelViewSet):
    """
    API endpoint that allows contracts types to be viewed or edited.
    """

    queryset = Contract.objects.all().order_by("abbrv")
    serializer_class = ContractSerializer


class JobViewSet(viewsets.ReadOnlyModelViewSet):
    """
    API endpoint that allows contracts types to be viewed or edited.
    """

    queryset = JobPosition.objects.all().order_by("name")
    serializer_class = JobSerializer


class OfferViewSet(viewsets.ReadOnlyModelViewSet):
    """
    API endpoint that allows offers to be viewed or edited.
    """

    queryset = (
        Offer.objects.select_related("contract", "place", "raw_offer")
        .all()
        .order_by("pub_date")
    )

    serializer_class = OfferSerializer


class PlaceVariationsViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Places used as reference to parse raw offers.
    """

    queryset = PlaceVariations.objects.all()
    serializer_class = PlaceVariationsSerializer


class PlaceViewSet(viewsets.ModelViewSet):
    """
    Places used as reference to parse raw offers.
    """

    queryset = Place.objects.all()
    serializer_class = PlaceSerializer


class TechnoViewSet(viewsets.ModelViewSet):
    """
    Places used as reference to parse raw offers.
    """

    queryset = Technology.objects.all()
    serializer_class = TechnoSerializer

elgeopaso/cms/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.views.decorators.cache import cache_page
from django.views.decorators.gzip import gzip_page
from django.views.decorators.http import require_safe

from elgeopaso.cms.models import Article, Category


@require_safe
@gzip_page
@cache_page(60 * 60)
def about(request):
    """Displays global metrics about database on homepage."""
    content = Article.objects.filter(published=1).first().content

    # values to replace within the template
    context = {
        "content": content,
    }

    # function end
    return render(request, "cms/about.html", context)


@require_safe
@gzip_page
@cache_page(60 * 60)
def docs(request):
    """Documentation content."""
    docs_list = Article.objects.filter(category="Documentation", published=1)

    return render(request, "cms/documentation.html", {"filter": docs_list})


@require_safe
@gzip_page
@cache_page(60 * 60)
def view_category(request, slug):
    category = get_object_or_404(Category, slug_name=slug)
    return render_to_response(
        "cms/category_detail.html",
        {
            "categories": Category.objects.all(),
            "category": category,
            "articles": Article.objects.filter(
                published=True, category=category
            ).order_by("-updated")[:5],
        },
    )


@require_safe
@gzip_page
@cache_page(60 * 60)
def view_article(request, slug, category):
    return render_to_response(
        "cms/article_detail.html",
        {"article": get_object_or_404(Article, slug_title=slug)},
    )

elgeopaso/templates/jobs/home.html
{% extends "base.html" %}
{% load admin_urls %}
{% load static %}
{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
	<div class="container">
		<h1>El Géo Paso</h1>
		<p>Statistiques dynamiques sur l'emploi en géomatique</p>
		<p>
			<a class="btn btn-primary btn-lg" href="{% url 'jobs:stats' %}" role="button">Consulter les statistiques</a>
			<br>
			<small class='text-muted'>sur les {{ nb_contrats }} offres parues du {{ first_date|date }} au {{ last_date }}</small>
		</p>
	</div>
</div>

<div class="container">
	<!-- Example row of columns -->
	<div class="row">
		<div class="col-md-4">
			<h2>Une base unique</h2>
			<p>Tout géomaticien·ne francophone qui se respecte connaît GeoRezo et passe tôt ou tard par le forum Job. Ce forum, incontournable sans être exhaustif, est représentatif du marché de l'emploi du secteur de l'information géographique.</p>
			<p>
				<a class="btn btn-default" href="https://georezo.net/forum/viewforum.php?id=10" role="button">Consulter le forum Job sur GeoRezo &raquo;</a>
			</p>
			<hr>
		</div>
		<div class="col-md-4">
			<h2>La démarche métier</h2>
			<p>Ce travail s'ancre dans la continuité de celui entamé par GeoRezo et l'AFIGéo depuis des années sur la reconnaissance des métiers de l'information géographique.</p>
			<p>
				<a class="btn btn-default" href="https://georezo.net/wiki/main/formetiers/dem_metiers" role="button">Consulter la démarche métiers &raquo;</a>
			</p>
			<hr>
		</div>
		<div class="col-md-4">
			<h2>Profession géomaticien·ne</h2>
			<p>Le métier de géomaticien n'a jamais été aussi dynamique… mais ce n'est pour autant pas facile de le décrire et de le faire connaître !<br>Dans la continuité des démarches de reconnaissance des métiers de la géomatique, l’AFIGÉO et GeoRezo proposent un nouvel espace d’expression : le blog « Géomaticien » !</p>
			<p>
				<a class="btn btn-default" href="https://georezo.net/blog/geomaticien/" role="button">Consulter le blog &raquo;</a>
			</p>
			<hr>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="text">
				<p class="lead">{{ presentation.content|safe }}</p>
			</div>
		</div>
	</div>
	<hr>
</div>
<!-- /container -->
<div class="row">
	<div class="col-lg-7 col-md-4">
		<h3 align="justify">Nom</h3>
		<div class="col-lg-2 col-md-1">
			<a class="thumbnail">
				<img src="{% static "jobs/img/logo_OldElPaso.jpg" %}" alt="Logo ElPaso" >
			</a>
		</div>
		<div class="col-lg-10 col-md-3" align="justify">
			Pourquoi El Paso ? Depuis des temps immémoriaux, le choix d'un nom de projet informatique est cornélien. Né autour de fajitas et de rhum, le nom El Paso s'est imposé comme une évidence. Bien traduit, il représente le petit pas qui sépare un demandeur d'emploi d'un poste. Une simple offre, un simple pas... non, en fait, rien de tout cela, c'était juste parce-que les fajitas étaient bonnes !
		</div>
	</div>

	<div class="col-lg-5 col-md-3">
		<h3 align="justify">Auteurs</h3>
		<div class="col-lg-3 col-md-1">
			<a class="thumbnail">
				<img src="{% static "jobs/img/logo_GeoTribu.png" %}" alt="Logo ElPaso" >
			</a>
		</div>
		<div class="col-lg-7" align="justify">
			<p>Dans l'esprit Geotribu, on avait envie de faire un projet utile en utilisant des technos sympas.</p>
			<div class="btn-group btn-group-justified" role="group">
			<a class="btn btn-default" href="https://www.linkedin.com/in/julienmoura" target="_blank" role="button">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span> Julien Moura
			</a>
			<a class="btn btn-default" href="https://www.linkedin.com/in/pierre-vernier-84437345" target="_blank" role="button">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span> Pierre Vernier
			</a>
			</div>
		</div>
	</div>
</div>

</div>

{% endblock content %}

elgeopaso/templates/jobs/map.html
{% extends "base.html" %}
{% load static %}
{% block custom_css %}
<link href='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css' rel='stylesheet' />
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div id='map-container'></div>
    </div>
</div>
{% endblock content %}
{% block custom_js %}
<script src='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js'></script>
<script type="text/javascript">
    var static_url = "{% get_static_prefix %}";
</script>
<script type="text/javascript" src="{% static 'jobs/js/map.js' %}" defer></script>
{% endblock %}

elgeopaso/templates/jobs/search.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load tpl_extras %}
{% block content %}
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Chercher dans les archives</h4>
      <div class="row">
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.date.label_tag }}
          {% render_field filter.form.date class="form-control" %}
        </div>
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.contract.label_tag }}
          {% render_field filter.form.contract class="form-control" %}
        </div>
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.place.label_tag }}
          {% render_field filter.form.place class="form-control" %}
        </div>
      </div>
      <div class="row">
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.technologies.label_tag }}
          {% render_field filter.form.technologies class="form-control" %}
        </div>
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.title.label_tag }}
          {% render_field filter.form.title class="form-control" %}
        </div>
        <div class="form-group col-sm-3 col-md-3">
          {{ filter.form.content.label_tag }}
          {% render_field filter.form.content class="form-control" %}
        </div>
         {% if user.is_authenticated %}
          <div class="form-group col-sm-3 col-md-3">
            {{ filter.form.raw_offer__to_update.label_tag }}
            {% render_field filter.form.raw_offer__to_update class="form-control" %}
          </div>
          {% endif %}
      </div>
      <button type="submit" class="btn btn-primary">
        <i class="fas fa-search"></i> Rechercher
      </button>
    </div>
  </form>
  <div>
    <p>{{ offers.paginator.count }} offres trouvées</p>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Titre</th>
        <th>Date de publication (RSS)</th>
        <th>Type de contrat reconnu</th>
        <th>Lieu reconnu</th>
        {% if user.is_authenticated %}
          <th>Corriger</th>
          <th>Nouvelle analyse</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for offer in offers %}
        <tr>
          <td>{{ offer.title }}</td>
          <td>{{ offer.pub_date|date }}</td>
          <td>{{ offer.contract }}</td>
          <td>{{ offer.place }}</td>
          {% if user.is_authenticated %}
          <td>
            <a target='_blank' href="{% url 'admin:jobs_georezorss_change' offer.id_rss %}">
              <button type="button" class="btn btn-circle"><i class="fas fa-pencil-alt" aria-hidden="true"></i></button>
            </a>
          </td>
          <td>{{ offer.raw_offer.to_update|yesno }}</td>
          {% endif %}
        </tr>
        {% empty %}
        <tr>
          <td colspan="5">Aucune offre ne correspond à la recherche</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="pagination">
    <nav aria-label="...">
      <ul class="pager">
        {% if offers.has_previous %}
          <li class="previous">
            <a href="?{% query_transform page=offers.previous_page_number %}"><span aria-hidden="true"><i class="fas fa-angle-left"></i> Précédente</a>
          </li>
        {% endif %}
        <span class="btn">Page {{ offers.number }} / {{ offers.paginator.num_pages }}</span>
        {% if offers.has_next %}
          <li class="next">
            <a href="?{% query_transform page=offers.next_page_number %}">Suivante <i class="fas fa-angle-right"></i><span aria-hidden="true"></a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endblock content %}

elgeopaso/templates/jobs/stats.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div id="wrapper">
      <!-- /.row -->
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-comments fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">{{ global_kpi.0 }}</div>
                  <div>Offres d'emploi répertoriées</div>
                </div>
              </div>
            </div>
            <a href="{% url 'jobs:timeline' %}">
              <div class="panel-footer">
                <span class="pull-left">Voir les 50 plus récentes</span>
                <span class="pull-right">
                  <i class="fas fa-arrow-circle-right"></i>
                </span>
                <div class="clearfix"></div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="panel panel-green">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fas fa-tasks fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">{{ global_kpi.1 }}%</div>
                  <div>ont un type de contrat reconnu</div>
                </div>
              </div>
            </div>
            <a href="/jobs/search?contract=ND">
              <div class="panel-footer">
                <span class="pull-left">Corriger les contrats</span>
                <span class="pull-right">
                  <i class="fas fa-arrow-circle-right"></i>
                </span>
                <div class="clearfix"></div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="panel panel-yellow">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fas fa-map-marked fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">{{ global_kpi.2 }}%</div>
                  <div>sont correctement localisées</div>
                </div>
              </div>
            </div>
            <a href="{% url 'jobs:map' %}">
              <div class="panel-footer">
                <span class="pull-left">Voir la carte</span>
                <span class="pull-right">
                  <i class="fas fa-arrow-circle-right"></i>
                </span>
                <div class="clearfix"></div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="panel panel-red">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fas fa-chart-line fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge">{{ global_kpi.3 }}%</div>
                  <div>d'offres par rapport à la même semaine l'an passé</div>
                </div>
              </div>
            </div>
            <a href="#title_types_contract_period">
              <div class="panel-footer">
                <span class="pull-left">Voir les tendances</span>
                <span class="pull-right">
                  <i class="fas fa-arrow-circle-down"></i>
                </span>
                <div class="clearfix"></div>
              </div>
            </a>
          </div>
        </div>
      </div>
      <!-- /.row -->
      <div class="row">
        <div class="col-lg-8">
          <div class="panel panel-default">
            <div class="panel-heading">
              <p id="title_contracts_type_pie"></p>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
              <svg  style="min-height: 450px;" id="chart_contracts_type_pie"></svg>
            </div>
            <!-- /.panel-body -->
          </div>
          <!-- /.panel -->
          <div class="panel panel-default">
            <div class="panel-heading">
              <p id="title_offers_period"></p>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
              <svg style="min-height: 400px;" id="chart_offers_period"> </svg>
            </div>
            <!-- /.panel-body -->
          </div>
          <!-- /.panel -->
          <div class="panel panel-default">
            <div class="panel-heading">
              <p id="title_types_contract_period"></p>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
              <svg style="min-height: 400px;" id="chart_types_contract_period"> </svg>
            </div>
            <!-- /.panel-body -->
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">
              <p id="title_technos_pie"></p>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
              <svg style="min-height: 400px;" id="chart_technos_pie"> </svg>
            </div>
            <!-- /.panel-body -->
          </div>
          <!-- /.panel -->
        </div>
        <!-- /.col-lg-8 -->
        <div class="col-lg-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <p id="title_fr_dpts_toms_pie"></p>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
              <svg style="min-height: 450px;" id="chart_fr_dpts_toms_pie"></svg>
            </div>
            <!-- /.panel-body -->
          </div>
          <!-- /.panel -->
          <div class="panel panel-default">
            <div class="panel-heading">
              <p id="title_countries_pie"></p>
            </div>
            <div class="panel-body">
              <svg style="min-height: 350px;" id="chart_countries_pie"> </svg>
            </div>
            <!-- /.panel-body -->
          </div>
        </div>
        <!-- /.col-lg-4 -->
      </div>
      <!-- /.row -->
    <!-- /#page-wrapper -->
</div>
{% endblock content %}
{% block custom_js %}
<script src="{% static 'jobs/js/contracts.js' %}"></script>
<script defer type="text/javascript">
  $( document ).ready(function() {
    // When page loads
    types_contract_global({{ contracts_types| safe }});
    contracts_by_french_dpts_toms();
    offers_by_period("year");
    types_contract_by_period("year");
    contracts_by_technos();
    contracts_by_countries();
  });
</script>
{% endblock %}