elgeopaso/cms/urls.py
#! python3  # noqa: E265  # noqa E265

"""
    Application URLs settings.
"""

# #############################################################################
# ########## Libraries #############
# ##################################

# Django
from django.conf.urls import url

from elgeopaso.cms import views

# #############################################################################
# ########### Globals ##############
# ##################################
urlpatterns = [
    url(r"^about/$", views.about, name="about"),
    url(r"^(?P<slug>[-\w]+)/$", views.view_category, name="view_category"),
    url(
        r"^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$",
        views.view_article,
        name="view_article",
    ),
]

elgeopaso/urls.py
#! python3  # noqa: E265  # noqa E265

"""
    Project URLs settings.

    Learn more here: https://docs.djangoproject.com/fr/2.2/topics/http/urls/

    To add a new path:

    .. code-block:: python

        # first import the app
        import jobs

        # then add the new path:
        path('jobs/', jobs.urls, name="Jobs offers")

"""

# #############################################################################
# ########## Libraries #############
# ##################################

# Django
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

# #############################################################################
# ########### Globals ##############
# ##################################
admin.autodiscover()


# List of accepted URLs
urlpatterns = [
    # administration panel
    path("admin/", admin.site.urls),
    # authentication flow
    path("accounts/", include("allauth.urls")),
    # Jobs analytics
    path("", include("elgeopaso.jobs.urls", "index"), name="home"),
    path("jobs/", include("elgeopaso.jobs.urls")),
    # CMS
    path("content/", include(("elgeopaso.cms.urls", "cms"), namespace="cms")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    # API
    path("api/", include(("elgeopaso.api.urls", "api"), namespace="api")),
]


# Addtionnal configuration for local development
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += [
    #     path(
    #         "400/",
    #         default_views.bad_request,
    #         kwargs={"exception": Exception("Bad Request!")},
    #     ),
    #     path(
    #         "403/",
    #         default_views.permission_denied,
    #         kwargs={"exception": Exception("Permission Denied")},
    #     ),
    #     path(
    #         "404/",
    #         default_views.page_not_found,
    #         kwargs={"exception": Exception("Page not Found")},
    #     ),
    #     path("500/", default_views.server_error),
    # ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

elgeopaso/cms/models.py
# 3rd party package
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator
from django.db import models
from django.template.defaultfilters import truncatechars
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Catégorie")
    slug_name = models.SlugField(verbose_name="Alias normé", unique=True, blank=True)
    description = models.TextField(blank=True, verbose_name="Description")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("view_category", kwargs={"slug": self.slug_name})

    class Meta:
        app_label = "cms"
        ordering = ["name"]
        verbose_name = "Type de contenu"
        verbose_name_plural = "Types de contenu"


class Article(models.Model):
    # meta
    author = models.ForeignKey(
        User, verbose_name="Auteur.e", null=True, on_delete=models.SET_NULL
    )
    category = models.ForeignKey(
        Category, verbose_name="Catégorie", null=True, on_delete=models.SET_NULL
    )
    # content
    title = models.CharField(
        "Titre", max_length=200, validators=[MaxLengthValidator(200)]
    )
    slug_title = models.SlugField(verbose_name="Alias normé", unique=True, blank=True)
    content = RichTextUploadingField("Corps de texte")
    ext_url = models.URLField("Lien externe", blank=True)
    published = models.BooleanField("Publié", blank=False, default=False)
    # dates
    created = models.DateTimeField("Créé le", auto_now_add=True)
    updated = models.DateTimeField("Modifié le", auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "cms:view_article",
            kwargs={"slug": self.slug_title, "category": self.category.slug_name},
        )
        # return "/content/{}/{}".format(self.category.slug_name, self.slug_title)

    @property
    def short_content(self):
        return truncatechars(self.content, 300)

    class Meta:
        app_label = "cms"
        get_latest_by = "updated"
        ordering = [
            "title",
        ]
        verbose_name = "Contenu éditorial"
        verbose_name_plural = "Contenus éditoriaux"

elgeopaso/cms/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.views.decorators.cache import cache_page
from django.views.decorators.gzip import gzip_page
from django.views.decorators.http import require_safe

from elgeopaso.cms.models import Article, Category


@require_safe
@gzip_page
@cache_page(60 * 60)
def about(request):
    """Displays global metrics about database on homepage."""
    content = Article.objects.filter(published=1).first().content

    # values to replace within the template
    context = {
        "content": content,
    }

    # function end
    return render(request, "cms/about.html", context)


@require_safe
@gzip_page
@cache_page(60 * 60)
def docs(request):
    """Documentation content."""
    docs_list = Article.objects.filter(category="Documentation", published=1)

    return render(request, "cms/documentation.html", {"filter": docs_list})


@require_safe
@gzip_page
@cache_page(60 * 60)
def view_category(request, slug):
    category = get_object_or_404(Category, slug_name=slug)
    return render_to_response(
        "cms/category_detail.html",
        {
            "categories": Category.objects.all(),
            "category": category,
            "articles": Article.objects.filter(
                published=True, category=category
            ).order_by("-updated")[:5],
        },
    )


@require_safe
@gzip_page
@cache_page(60 * 60)
def view_article(request, slug, category):
    return render_to_response(
        "cms/article_detail.html",
        {"article": get_object_or_404(Article, slug_title=slug)},
    )

elgeopaso/cms/templates/cms/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
  <div class="text">{{ content|safe }}</div>
{% endblock content %}

elgeopaso/cms/templates/cms/article_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
                <h1>{{article.title}}</h1>{% if user.is_authenticated %}<a target='_blank' href="{% url 'admin:cms_article_change' article.id %}">
                    <button type="button" class="btn btn-circle">
                        <i class="fas fa-pencil" aria-hidden="true"></i>
                    </button>
                </a> {% endif %}
                <hr>
                <p  class='text-muted'>
                    Catégorie : <a href="{% url 'cms:view_category' slug=article.category.slug_name %}">{{article.category}}</a>
                    - De : {{ article.author.first_name }}
                    <br><i class='far fa-calendar'></i> Créé le {{ article.created|date }} -
                    <i class='far fa-clock'></i> Mis à jour le {{ article.updated|date }}
                </p>
                <hr>
                <!-- <img class="img-responsive" src="http://placehold.it/900x300" alt=""><hr> -->
                <div class="text"><p class="lead">{{ article.content|safe }}</p></div>
                <hr>
            </div>
        </div>
        <!-- /.row -->

        <hr>
    </div>
{% endblock %}

elgeopaso/cms/templates/cms/category_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">
            <h1 class="page-header">
                 {{ category.name }}
                <small>{{ category.description }}</small>
            </h1>
            <hr>
            {% for art in articles %}
                <h2><a href="{% url 'cms:view_article' slug=art.slug_title category=art.category %}">{{ art.title }}</a></h2>
                <p class='text-muted'>
                <i class='far fa-calendar'></i> Créé le {{ art.created|date }} -
                <i class='far fa-clock'></i> Mis à jour le {{ art.updated|date }}
                </p>
                <p>{{art.content|truncatechars:150|safe}}</p>
                <a class="btn btn-primary" href="{% url 'cms:view_article' slug=art.slug_title category=art.category %}">Lire
                    <i class='fas fa-glasses'></i>
                </a>

            {% endfor %}

            <hr>
        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Blog Search Well -->
            <div class="well">
                <h4>Blog Search</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Blog Categories</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li>
                                <a href="#">Category Name</a>
                            </li>
                            <li>
                                <a href="#">Category Name</a>
                            </li>
                            <li>
                                <a href="#">Category Name</a>
                            </li>
                            <li>
                                <a href="#">Category Name</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li>
                                <a href="#">Category Name</a>
                            </li>
                            <li>
                                <a href="#">Category Name</a>
                            </li>
                            <li>
                                <a href="#">Category Name</a>
                            </li>
                            <li>
                                <a href="#">Category Name</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>

            <!-- Side Widget Well -->
            <div class="well">
                <h4>Side Widget Well</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium
                    odit aliquam repellat tempore quos aspernatur vero.</p>
            </div>

        </div>

    </div>

</div>


{% endblock %}